# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://euroclojure.org
title: EuroClojure 2016
email: events@cognitect.com
description: > # "EuroClojure 2016"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:title

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/EuroClojure